server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: kheang

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis_config.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

logging:
  file:
    path: CustomerService.log
